# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:  http://columns.chicken-house.net
date_format: "ordinal"
title: 安德魯的部落格
subtitle: "架構師的修練"

# for SEO, 會標記在首頁的 meta tags 內
description: "安德魯的部落格"
keywords: .NET,C#,OOP,Azure,Docker,Windows Container,Container,Microservices

favicon: 
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Andrew Wu
organization: 
organization_url: 
github_username: andrew0928
location: Taipei, Taiwan
email: chicken@chicken-house.net

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁

  -
    href: /tags/
    label: 標籤

  -
    href: /categories/
    label: 主題分類

#  -
#    href: /wiki/
#    label: Wiki

#  -
#    href: /links/
#    label: Links

  -
    href: /codes/
    label: 我的程式碼

  -
    href: /about/
    label: 關於我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 5
lsi: false
quiet: false
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:slug/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: disqus

# !!!Important!!! Please modify infos below to yours
disqus_username: andrew0928
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-68797023-1


# script
debug: false